### ISSUE TITLE
[BUG] Cannot Change Theme Link On Vencord.

### ISSUE THREAD

**Issue by Ratlsk** [Slddev/SpotiCord#7]
### Description of bug

It doesnt let me take off the theme

### Steps to reproduce

Put the theme on Vencord themes

### Screenshots

![Screenshot 2023-03-23 201611](https://user-images.githubusercontent.com/128762965/227399765-4502b2f8-139a-4e21-84cf-5496233b0888.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheDoDoo** [comment]
Hi @Ratlsk,
You can remove the theme so.

> Go to 
![grafik](https://user-images.githubusercontent.com/96340450/227721035-61e566d9-f47e-456f-beaf-daa0b0860100.png)
> 
![grafik](https://user-images.githubusercontent.com/96340450/227720995-44be9c5e-8920-4255-af38-5755e01c91ad.png)

**Comment by TheDoDoo** [comment]
Hello @Ratlsk,
You can remove the theme like this:

> Go To Settings and then to Vencord
![grafik](https://user-images.githubusercontent.com/96340450/227721111-8334a8b0-c9ed-4238-b7a2-bb2bedc2c68b.png)

> Then klick `Open Settings Folder`
![grafik](https://user-images.githubusercontent.com/96340450/227721149-99c8ee0c-8bc1-419e-a75e-e5ea2906efc5.png)

> Then go in The Folder `Settings`
![grafik](https://user-images.githubusercontent.com/96340450/227721167-206b08eb-cae9-49b9-8237-a2949038bdbb.png)

> Now Open the `settings.json` with a text editor
![grafik](https://user-images.githubusercontent.com/96340450/227721302-52c666cc-1813-46fd-852e-906229585ccd.png)

> Now overwrite the line `6` with `"themeLinks": [],` as shown in picture

> Save the file (STRG + S)

> Relode Discord (STRG + R)

> Now you are in Defult Theme

**Comment by Slddev** [comment]
Thank you @TheDoDoo for explaining how.

**Comment by lewisakura** [comment]
After some investigation, this issue is caused by this style rule here:

https://github.com/Slddev/SpotiCord/blob/af768bbb3960553db5b6128a69cdf972e2da4504/src/Popouts/index.css#L7-L15

It then later reverts this rule for the user notes section:

https://github.com/Slddev/SpotiCord/blob/af768bbb3960553db5b6128a69cdf972e2da4504/src/Popouts/index.css#L69-L73

This is a really poorly written style rule and should be more specific to whatever it's trying to target, rather than blanket removing these textarea components, and should be considered an issue with the theme in general. I'd recommend just removing the `.textarea-` rule here since it seems to cause no harm to the theme's design when its disabled. If you really want to keep that, then you should add `.textarea-_59yqs[placeholder="Theme Links"]` to the revert rule as well. It seems like [you special case some mods](https://github.com/Slddev/SpotiCord/blob/af768bbb3960553db5b6128a69cdf972e2da4504/src/Plugins/index.css) so it could also be inserted here.
